### ISSUE TITLE
Docs or roadmap?

### ISSUE THREAD

**Issue by bursaar** [Anthogonyst/UnityToGodot#1]
Since the material created by a team of developers for a Unity game exist mostly in accessible formats (YAML, text, media) there're a lot of different ways to approach this. Do you have a roadmap or a proposed approach? This project is less than 24 hours old, so no problem if not! Should some kind of tech plan or proposal be hashed out so we can co-ordinate efforts?

**Comment by Anthogonyst** [comment]
It's a great idea. I was thinking of making a public Trello when the ideas are on paper and the plan seems solid. Before that I'm wondering what we should use besides the discord? Any suggestions?

As far as what I'm thinking of currently, I think that we need a few kinds of text parsers to convert alot of raw data (scenes, animation keyframes, etc) to JSON, a middle step that reshapes the data in a form easily digestible to Godot (child transform to spatials, etc), and then lastly figure out what existing Godot tool accepts that JSON as an input.

**Comment by Anthogonyst** [comment]
Hi there, I'm back and I have a roadmap that I proposed to the discord community. I'm taking suggestions and feedback.
![UnityToGodotRoadmap](https://github.com/Anthogonyst/UnityToGodot/blob/master/docs/images/UnityToGodotRoadmap.png)
