### ISSUE TITLE
Consider writing unit tests to unity-godot-compat

### ISSUE THREAD

**Issue by GeorgeS2019** [Anthogonyst/UnityToGodot#4]
using the [latest](https://github.com/MikeSchulze/gdUnit4Mono/pull/37) gdUnit4API **TestAdaptor** on VS2022

![Z0nhScGr3J](https://github.com/MikeSchulze/gdUnit4Mono/assets/49812372/7d2ed607-0750-4b6e-80f7-e5913aec040e)

**Comment by Anthogonyst** [comment]
Thank you. Could you explain how to use this tool? Is it exclusive to VS or is it possible to use it standalone within the repo? If it is plausible to use this without interfacing with an IDE (as IDE preference is tailored to the individual and not to a general project), I would consider adding a symlink to it.

**Comment by GeorgeS2019** [comment]
>  If it is plausible to use this without interfacing with an IDE (as IDE preference is tailored to the individual and not to a general project),

Right now, both **Rider** and **VS2022** support it.

>  Is it possible to use it standalone within the repo?

 May be this will help
https://github.com/godotengine/godot-csharp-visualstudio/issues/53#issuecomment-1987338578

Many users are helping to make it robust and join the **Discord**

**Comment by Anthogonyst** [comment]
So when I asked if it works without an IDE, you suggested to use a different IDE. Right. So while I appreciate the interest, I'm gonna close this now. Thank you.
